### ISSUE TITLE
AWS IAM  authentication token as password?

### ISSUE THREAD

**Issue by ngvirus** [tlocke/pg8000#14] opened 2019-05-02 13:29 UTC
Hello,

So I'm facing an issue while trying to authenticate to aws aurora postgresql cluster with IAM token. The token is 1200+ chars and it's supposed to be used as 'password', this works with psql, but it doesn't work with pg8000. Can you tell me if there's any length limitations on the password?

**Comment by riamaria** [comment] 2019-11-04 22:17
@ngvirus I don't see any password length checks in https://github.com/tlocke/pg8000/blob/master/pg8000/core.py

Do you have any more information such as logs or a stack trace that explains why your password doesn't work?

**Comment by ngvirus** [comment] 2019-11-05 15:23
Hello,
Well the lambda i was testing worked with passwords up to 50 chars, but when i used AWS AUTH token similar to this one: some-rds.in.aws.eu-central-1.amazon.com:5432/?Action=connect&DBUser=jane_doe&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIARZEXTHVCXK2126U3%2F20191105%2Fus-west-2%2Frds-db%2Faws4_request&X-Amz-Date=20191105T151443Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=f3fab13615e52bda9351b1401bf3f44a7083e08f70aef3dcadfef2e0f7c3964c
All i got was wrong password. 
I no longer work on this and i don't have access to the logs from when i worked on it. Also I've tried every solution that works with  DB-API 2.0 and none of them works, but solutions that use the postgresql static library work fine, but they don't work on AWS Lambda

**Comment by oguzhanogreden** [comment] 2019-11-20 11:43
I'm having the same issue. The auth token similar to the one reported by @ngvirus won't work. If I enter the password manually for testing, it works.

**Comment by tlocke** [comment] 2020-02-21 11:52
A couple of ideas:

- The `user`, `password` and `database` parameters are sent to the server as bytes. If you give the parameters to pg8000 as `str`, then pg8000 encodes them as utf8 bytes before sending them to the server. So one thing to check is the encoding of the database. If it's not ascii or utf8 then you need to give pg8000 the parameters as bytes (see docs).
- The other thing is that Python string literals can have escape sequences. So this could be tripping things up if there happen to be escape sequences in your password.
- If the above doesn't solve it, then the next step is to reproduce the bug locally with an instance of PostgreSQL. I'd probably start by altering pg8000 to print out the bytes that are being sent, and checking that this is what you expect.

Hope that helps!

**Comment by durzo** [comment] 2020-10-16 08:51
This is working for me with no additional encoding needed.
If you are seeing a `PAM authentication failed` error, ensure you have the correct IAM policy attached to your lambda/ec2

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "rds-db:connect",
            "Resource": "*"
        }
    ]
}
```

Resource should be more specific in a production environment, refer to aws docs here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html

**Comment by tlocke** [comment] 2021-03-06 09:48
It doesn't look like this is a problem with pg8000, but more to do with AWS configuration, so I'll close this issue. Feel free to re-open if it's still a problem though.

**Comment by tlocke** [comment] 2021-03-06 09:48
It doesn't look like this is a problem with pg8000, but more to do with AWS configuration, so I'll close this issue. Feel free to re-open if it's still a problem though.

**Comment by Navbryce** [comment] 2022-10-01 00:33
It's not working for IAM authentication on my side. I'm pretty sure it's the library because I got it to connect with the same python variables using subprocess.check_output and psql.

**Comment by tlocke** [comment] 2022-10-01 06:19
Hi @Navbryce, is there some way to narrow down what might be the problem? The thing is that we need to pin down exactly what's going wrong in order to fix it. Also, perhaps Amazon may be able to help, it may be worth getting in touch with them as they use pg8000 (eg in https://github.com/aws/aws-sdk-pandas).

**Comment by Navbryce** [comment] 2022-10-01 09:16
> Hi @Navbryce, is there some way to narrow down what might be the problem? The thing is that we need to pin down exactly what's going wrong in order to fix it. Also, perhaps Amazon may be able to help, it may be worth getting in touch with them as they use pg8000 (eg in https://github.com/aws/aws-sdk-pandas).

Sorry for not giving a lot to go off of; I hadn't put enough time into my own investigation. After playing around with it a bit more, I've discovered it has to do with SSL -- there doesn't seem to be anything wrong with pg8000. Sorry about that 😄 

For anyone that runs into the issue:
```
    ssl_context = ssl.create_default_context()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE
```
and passing that `ssl_context` to the connection worked. Pg8000 was able to connect! Obviously, running without certificate verification is not secure, but it's a good sanity check to see what's happening.

**Comment by tlocke** [comment] 2022-10-01 16:26
Excellent! Glad you solved it.

**Closed by tlocke** 2022-10-01 16:26 UTC

**Comment by AzySir** [comment] 2025-07-21 23:17
I have this issue also - has anyone got sample code anywhere ? I'm getting the PAM issue!
